/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import magick.ImageInfo;
import magick.MagickImage;
import magick.MagickException;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;


public class App {
    public static byte[] optimizeAndResize(byte[] inputImageBytes, int width, int height)
            throws MagickException, IOException {

        // Read the image from the byte array
        ImageInfo imageInfo = new ImageInfo();
        MagickImage image = new MagickImage(imageInfo, inputImageBytes);

        // Resize the image
        MagickImage resizedImage = image.scaleImage(width, height);

        // Write the resized image to the output byte array
        Path outputFile = Files.createTempFile("outputTemp", ".jpg");
        ImageInfo outputImageInfo = new ImageInfo(outputFile.toString());
        resizedImage.writeImage(outputImageInfo);


        // Return the output byte array
        var outputBytes = Files.readAllBytes(outputFile);
        Files.delete(outputFile);
        return outputBytes;
    }

    public static void main(String[] args) throws Exception {
               // Example usage
        byte[] inputImage = Files.readAllBytes(Paths.get("test.jpg")); // Load your image as byte array
        int width = 800;
        int height = 600;

        try {
            byte[] outputImage = optimizeAndResize(inputImage, width, height);
            Files.write(Paths.get("out.jpg"), outputImage);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
