/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import magick.ImageInfo;
import magick.MagickException;
import magick.MagickImage;

public class App {
    public static byte[] optimizeAndResize(byte[] inputImageBytes, int width, int height)
            throws MagickException, IOException {
        System.out.println("Input image size: " + inputImageBytes.length);
        // Read the image from the byte array
        Path inputFile = Files.createTempFile("inputTemp", ".jpg");
        Files.write(inputFile, inputImageBytes);
        ImageInfo imageInfo = new ImageInfo(inputFile.toString());
        MagickImage image = new MagickImage(imageInfo);

        // Resize the image
        MagickImage resizedImage = image.scaleImage(width, height);

        // Write the resized image to the output byte array
        Path outputFile = Files.createTempFile("outputTemp", ".jpg");
        ImageInfo outputImageInfo = new ImageInfo(outputFile.toString());
        resizedImage.writeImage(outputImageInfo);

        // Return the output byte array
        var outputBytes = Files.readAllBytes(outputFile);
        System.out.println("Output image size: " + outputBytes.length);

        // Clean up
        Files.delete(inputFile);
        Files.delete(outputFile);

        return outputBytes;
    }

    public static void main(String[] args) throws Exception {
        // Example usage
        byte[] inputImage = Files.readAllBytes(Paths.get("test.jpg")); // Load your image as byte array
        int width = 800;
        int height = 600;

        try {
            byte[] outputImage = optimizeAndResize(inputImage, width, height);
            Files.write(Paths.get("out.jpg"), outputImage);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
