/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import magick.ImageInfo;
import magick.MagickException;
import magick.MagickImage;

public class App {
    public static byte[] optimizeAndResize(byte[] inputImageBytes, int width, int height)
            throws Exception {
        System.out.println("Input image size: " + inputImageBytes.length);
        // Read the image from the byte array
        ImageInfo imageInfo = new ImageInfo();
        MagickImage image = new MagickImage(imageInfo, inputImageBytes);

        // Resize the image
        MagickImage resizedImage = image.scaleImage(width, height);

        // Write the resized image to the output byte array
        imageInfo.setQuality(80); // Set the quality to 80%
        var outputBytes = resizedImage.imageToBlob(imageInfo);

        System.out.println("Output image size: " + outputBytes.length);
        return outputBytes;
    }

    public static void main(String[] args) throws Exception {
        // Example usage
        byte[] inputImage = Files.readAllBytes(Paths.get("test.jpg")); // Load your image as byte array
        int width = 800;
        int height = 600;

        try {
            byte[] outputImage = optimizeAndResize(inputImage, width, height);
            Files.write(Paths.get("out.jpg"), outputImage);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
